[workspace]
members = [
    "crates/clawlet-core",
    "crates/clawlet-signer",
    "crates/clawlet-evm",
    "crates/clawlet-ipc",
    "crates/clawlet-cli",
    "tests/integration",
]
resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "MIT"
